name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      NodeVersion: 20.x

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NodeVersion }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NodeVersion }}
          cache: 'npm'
      - run: npm install
      - run: npm run lint
