# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      NodeVersion: 14 # Change this to your desired Node.js version
      GoVersion: ^1.21.4

    steps:
      - uses: actions/checkout@v3

      - name: Use Go ${{ env.GoVersion }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GoVersion }}

      - run: go mod download
        working-directory: ./cli

      - name: Use Node.js ${{ env.NodeVersion }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NodeVersion }}
          cache: 'npm'

      - run: npm i

      - name: Start Electron Forge
        run: npm run forge:start

      - name: Package Electron Forge
        run: npm run forge:package

      - name: Make Electron Forge
        run: npm run forge:make

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: out/make
